#!/bin/bash
echo -e "\e[34mClone \e[34mOhGodAnETHlargementPill\n"
git clone https://github.com/LukasBures/OhGodAnETHlargementPill.git
sudo chmod a+x ./OhGodAnETHlargementPill/OhGodAnETHlargementPill
sudo cp ./OhGodAnETHlargementPill/OhGodAnETHlargementPill /usr/local/bin/
sudo cp ./OhGodAnETHlargementPill.service /etc/systemd/system/
echo -e "\e[34mreload \e[34mdaemons"
systemctl daemon-reload
echo -e "\e[34menable \e[34mOhGodAnETHlargementPill.service"
systemctl enable OhGodAnETHlargementPill.service
echo -e "\e[34mstart \e[34mOhGodAnETHlargementPill.service"
systemctl start OhGodAnETHlargementPill.service
